databases:
  - name: rapture-db
    plan: free
    databaseName: rapture
    user: rapture

services:
  - type: web
    plan: free
    name: rapture-by-rj-rapture-labs
    runtime: node
    buildCommand: npm install --include=dev && npm run build && npm run db:push
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rapture-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
