import { storage } from "./storage";
import { db } from "./db";
import { chroniclesPosts } from "@shared/schema";
import { randomUUID } from "crypto";

export async function seedDatabase() {
  const existingChars = await storage.getCharacters();
  if (existingChars.length > 0) return;

  console.log("Seeding Chronicles Reborn data...");

  await storage.createCharacter({ name: "David", role: "Warrior King", description: "The shepherd who defeated a giant with faith and a sling. David's courage in battle is matched only by his devotion to God. He leads with a warrior's heart and a psalmist's soul.", signatureAbility: "Sling of Zion — Launches divine projectiles that pierce enemy armor and stun champions.", faithStyle: "Praise Warrior", battleSpecialty: "Long-range precision & giant slaying", color: "#f59e0b" });
  await storage.createCharacter({ name: "Samson", role: "Nazirite Powerhouse", description: "Blessed with supernatural strength from birth, Samson is an unstoppable force in close combat. When the Spirit moves him, entire armies cannot stand.", signatureAbility: "Lion's Roar — Unleashes a shockwave that knocks back all enemies in a wide radius.", faithStyle: "Spirit-Empowered", battleSpecialty: "Melee dominance & crowd control", color: "#dc2626" });
  await storage.createCharacter({ name: "Joshua", role: "Covenant Commander", description: "Moses' chosen successor who led Israel into the Promised Land. Joshua commands with strategic brilliance and unwavering obedience to divine instruction.", signatureAbility: "Shout of Jericho — A battle cry that crumbles enemy fortifications and breaks curses.", faithStyle: "Bold Obedience", battleSpecialty: "Siege warfare & army commander buffs", color: "#2563eb" });
  await storage.createCharacter({ name: "Gideon", role: "Unlikely Champion", description: "Called while hiding in a winepress, Gideon rose to defeat the Midianites with just 300 men and the light of God. He proves that with faith, the few can overcome the many.", signatureAbility: "Torches in the Night — Reveals hidden enemies and blinds opposing forces with holy light.", faithStyle: "Reluctant Courage", battleSpecialty: "Stealth tactics & outnumbered battles", color: "#16a34a" });
  await storage.createCharacter({ name: "Elijah", role: "Prophet of Fire", description: "Called fire from heaven and stood alone against hundreds of false prophets. Elijah is a spiritual powerhouse whose faith can literally change the weather.", signatureAbility: "Heaven's Flame — Calls down pillars of fire that devastate enemy formations.", faithStyle: "Prophetic Authority", battleSpecialty: "Elemental attacks & spiritual warfare", color: "#ea580c" });
  await storage.createCharacter({ name: "Holy Spirit", role: "Divine Empowerment", description: "The ultimate source of power for every Chronicles hero. When invoked, the Holy Spirit transforms any warrior into an unstoppable vessel of divine might.", signatureAbility: "Pentecost Rush — Fills all allies with divine fire, doubling their power and granting immunity.", faithStyle: "Pure Anointing", battleSpecialty: "Team buff & ultimate transformation", color: "#7c3aed" });

  await storage.createBattle({ title: "David vs Goliath", description: "The defining battle of faith over fear. Armed with only a sling and five stones, young David faces the nine-foot giant who has terrorized Israel for forty days.", heroes: ["David"], enemies: ["Goliath"], scripture: "1 Samuel 17:45-47", difficulty: "legendary", featured: true });
  await storage.createBattle({ title: "Fall of Jericho", description: "March around the walls seven times. On the seventh day, blow the trumpets. When the people shouted, the walls of the greatest fortress in Canaan crumbled to dust.", heroes: ["Joshua"], enemies: ["Jericho Army"], scripture: "Joshua 6:20", difficulty: "epic", featured: true });
  await storage.createBattle({ title: "Crossing the Red Sea", description: "With Pharaoh's army behind and the sea before them, God made a way where there was no way. Moses stretches out his staff and the waters divide.", heroes: ["Moses"], enemies: ["Pharaoh's Army"], scripture: "Exodus 14:21-22", difficulty: "legendary", featured: true });
  await storage.createBattle({ title: "Elijah vs Prophets of Baal", description: "450 prophets of Baal vs. one man and his God. One prayer from Elijah and fire fell from heaven and consumed everything — altar, stones, water, and all.", heroes: ["Elijah"], enemies: ["Prophets of Baal"], scripture: "1 Kings 18:36-38", difficulty: "epic", featured: true });
  await storage.createBattle({ title: "Samson and the Philistines", description: "Captured, blinded, and chained — yet Samson's greatest act of faith came at his weakest moment. His final prayer brought the entire temple crashing down.", heroes: ["Samson"], enemies: ["Philistine Army"], scripture: "Judges 16:28-30", difficulty: "epic", featured: false });
  await storage.createBattle({ title: "Gideon's 300", description: "God told Gideon to reduce his 32,000 soldiers to just 300. Armed only with trumpets and torches, this tiny force routed the massive Midianite army.", heroes: ["Gideon"], enemies: ["Midianite Army"], scripture: "Judges 7:20-22", difficulty: "hard", featured: false });
  await storage.createBattle({ title: "Battle of Ai", description: "After learning from defeat, Joshua leads a brilliant ambush strategy against the city of Ai. Strategy, faith, and obedience combine for a decisive victory.", heroes: ["Joshua"], enemies: ["Army of Ai"], scripture: "Joshua 8:18-19", difficulty: "medium", featured: false });
  await storage.createBattle({ title: "David and the Lion", description: "Long before Goliath, David faced a lion threatening his sheep. With bare hands and faith, the young shepherd proved his heart was ready for greater battles.", heroes: ["David"], enemies: ["Lion of the Valley"], scripture: "1 Samuel 17:34-37", difficulty: "medium", featured: false });
  await storage.createBattle({ title: "Jehoshaphat's Praise March", description: "When three armies surrounded Judah, God gave a strange battle plan: send singers first. As worship went before the army, the enemies turned on each other.", heroes: ["Jehoshaphat"], enemies: ["Coalition of Three Armies"], scripture: "2 Chronicles 20:21-23", difficulty: "hard", featured: false });
  await storage.createBattle({ title: "Jacob Wrestles the Angel", description: "A night-long spiritual wrestling match that changed a man's identity forever. Jacob would not let go until he received a blessing — and walked away both wounded and renamed.", heroes: ["Jacob"], enemies: ["The Angel of God"], scripture: "Genesis 32:24-30", difficulty: "legendary", featured: false });

  const postsData = [
    { authorName: "FaithArtist_RJ", title: "My David vs Goliath Fan Art — 3 Days of Work!", content: "Finally finished this piece after 72 hours of drawing. David with the sling right before the throw — the light behind him represents God's presence. This game inspired me spiritually and artistically. Chronicles Reborn changed the way I see these stories.", category: "Fan Art", tags: ["david", "goliath", "fanart", "digitalart"], heroTag: "David", battleTag: "David vs Goliath", featured: true, likes: 247, comments: 34, shares: 18 },
    { authorName: "StrategistKing", title: "How to Beat Goliath on Legendary Mode — Full Guide", content: "After 40 attempts, I cracked the legendary code. The key is timing the sling charge right as Goliath starts his stomp animation. You get a 0.3 second window. Here's the full breakdown with timestamps...", category: "Strategy Guide", tags: ["strategy", "david", "goliath", "legendary", "guide"], heroTag: "David", battleTag: "David vs Goliath", featured: true, likes: 189, comments: 52, shares: 41 },
    { authorName: "ProphetFlame", title: "Elijah's Fire Power Is INSANE — Gameplay Breakdown", content: "Just uploaded my best Elijah run. Heaven's Flame at full faith meter does 10x damage. The secret is building faith through the worship segments before the boss fight. Watch this...", category: "Gameplay Clip", tags: ["elijah", "gameplay", "fire", "boss"], heroTag: "Elijah", battleTag: "Elijah vs Prophets of Baal", featured: true, likes: 312, comments: 67, shares: 55 },
    { authorName: "ScriptureScholar", title: "The Theology Behind Chronicles Reborn — A Deep Dive", content: "I'm a seminary student and this game is theologically fascinating. The way they've incorporated actual scripture into battle mechanics is unlike anything I've seen in faith-based gaming. Thread: Why Chronicles Reborn matters...", category: "Bible Reflection", tags: ["theology", "scripture", "analysis", "faith"], featured: false, likes: 156, comments: 89, shares: 72 },
    { authorName: "GideonFan300", title: "Gideon's 300 Animation I Made", content: "Created this short animation of the torches scene in Gideon's battle. The moment those torches light up in the darkness gave me chills. Had to recreate it in After Effects.", category: "Animation", tags: ["gideon", "animation", "300", "midianites"], heroTag: "Gideon", featured: false, likes: 203, comments: 28, shares: 31 },
    { authorName: "JoshuaCommander", title: "My Jericho Battle Reaction — I Was NOT Ready", content: "SPOILER: The moment the walls actually collapse in the game — the rumble controller feedback, the audio design — I literally had to pause and just sit there. This game hit different. React video coming tomorrow.", category: "Battle Reaction", tags: ["jericho", "reaction", "joshua", "walls"], heroTag: "Joshua", battleTag: "Fall of Jericho", featured: false, likes: 178, comments: 43, shares: 27 },
    { authorName: "HolyMusicMaker", title: "Original Track Inspired by Chronicles — 'Red Sea'", content: "I wrote and produced this track after playing the Crossing the Red Sea level. The tension of the water walls, the urgency of the escape — I tried to capture all of it musically. Sharing it with the community.", category: "Music Inspired by Chronicles", tags: ["music", "redsea", "original", "soundtrack"], battleTag: "Crossing the Red Sea", featured: true, likes: 134, comments: 19, shares: 44 },
    { authorName: "CharacterDesigner", title: "My Samson Redesign — What If He Had Armor?", content: "Redesigned Samson with what I imagine his armor would look like if he wore any. Still left the flowing hair as the power source but gave him a more imposing physical presence. Based on Philistine military aesthetics.", category: "Character Edit", tags: ["samson", "redesign", "characterdesign", "fanart"], heroTag: "Samson", featured: false, likes: 221, comments: 37, shares: 29 },
    { authorName: "SpiritualGamer_X", title: "Samson's Final Stand Made Me Cry — Not Ashamed", content: "The temple scene hit so different. When Samson prays that final prayer and the pillars crack... the music swells... I had tears streaming. This game doesn't just entertain, it ministers. The devs understood the weight of that moment.", category: "Battle Reaction", tags: ["samson", "emotional", "temple", "faith"], heroTag: "Samson", battleTag: "Samson and the Philistines", featured: true, likes: 287, comments: 91, shares: 63 },
    { authorName: "ArtOfWar_Faith", title: "Joshua Character Concept — Commander Armor Edition", content: "Imagined Joshua in full Israelite commander armor with Covenant symbols etched into the breastplate. The blade has Joshua 1:9 engraved on it. Took me two weeks to get the lighting right. Hope the devs see this.", category: "Fan Art", tags: ["joshua", "fanart", "concept", "armor"], heroTag: "Joshua", featured: false, likes: 198, comments: 24, shares: 19 },
    { authorName: "SpeedrunSaints", title: "David vs Goliath Speedrun — 47 Seconds (World Record?)", content: "Optimized the entire David vs Goliath fight to 47 seconds flat. The trick is to skip the first taunt animation by dashing left immediately, then charging the sling during Goliath's roar. Frame-perfect but doable.", category: "Gameplay Clip", tags: ["speedrun", "david", "goliath", "worldrecord"], heroTag: "David", battleTag: "David vs Goliath", featured: false, likes: 341, comments: 73, shares: 88 },
    { authorName: "PrayerWarrior_777", title: "How Chronicles Made Me Read 1 Kings Again", content: "I played the Elijah vs Baal level three times because I wanted to feel that fire fall moment again. Then I opened 1 Kings 18 for the first time in years. This game is doing something the church should pay attention to. Scripture through gameplay works.", category: "Bible Reflection", tags: ["elijah", "baal", "scripture", "testimony"], heroTag: "Elijah", battleTag: "Elijah vs Prophets of Baal", featured: false, likes: 176, comments: 58, shares: 45 },
    { authorName: "NightPixelArt", title: "Gideon Pixel Art — Torch in the Darkness", content: "Made a pixel art version of Gideon holding his torch high. Went for a retro 16-bit SNES style. The way the torch light illuminates the 300 soldiers behind him in the dark... that imagery stuck with me from the game.", category: "Fan Art", tags: ["gideon", "pixelart", "retro", "torch"], heroTag: "Gideon", battleTag: "Gideon's 300", featured: false, likes: 164, comments: 22, shares: 16 },
    { authorName: "FaithComboMaster", title: "Elijah Full Combo Chain — All Abilities Linked", content: "Found a way to chain all of Elijah's abilities into one continuous combo. Heaven's Flame into Prophet's Sprint into Mantle Strike. If you time the faith meter correctly, you get a hidden finisher move.", category: "Gameplay Clip", tags: ["elijah", "combo", "abilities", "guide"], heroTag: "Elijah", featured: false, likes: 256, comments: 44, shares: 39 },
    { authorName: "TheAnointedBrush", title: "Holy Spirit Character Illustration — Full Body", content: "This was the hardest character to visualize. How do you draw the Holy Spirit? I went with a luminous figure of pure divine energy — no fixed form, just light, wind, and fire converging into something beyond human comprehension.", category: "Fan Art", tags: ["holyspirit", "illustration", "divine", "fanart"], heroTag: "Holy Spirit", featured: true, likes: 389, comments: 76, shares: 54 },
    { authorName: "VerseBattle", title: "Why the Scripture Integration Actually Works", content: "Most faith games slap a Bible verse on a loading screen and call it a day. Chronicles Reborn actually builds game mechanics around scripture. David's sling power scales with the verses you memorize in-game. That's genius design.", category: "Theory / Lore", tags: ["gamedesign", "scripture", "analysis", "mechanics"], featured: false, likes: 145, comments: 67, shares: 38 },
  ];

  for (const p of postsData) {
    await db.insert(chroniclesPosts).values({ id: randomUUID(), moderationStatus: "approved", ...p } as any);
  }

  await storage.createChallenge({ title: "Draw David vs Goliath", slug: "draw-david-vs-goliath", description: "Create your most epic fan art of the greatest underdog battle in history. Show us David right before the throw — the faith, the focus, the moment everything changes. Any medium welcome: digital, traditional, or mixed.", type: "fan art", theme: "David vs Goliath", rewardText: "Giant Slayer Badge + Exclusive Wallpaper Pack", status: "active", startDate: new Date("2026-03-01"), endDate: new Date("2026-03-31") } as any);
  await storage.createChallenge({ title: "Jericho Battle Clip", slug: "jericho-battle-clip", description: "Record and share your most epic Jericho gameplay moment. The wall collapse, the charge through the gates, or the final confrontation inside the city — we want your best footage.", type: "clip", theme: "Fall of Jericho", rewardText: "Wall Breaker Badge + Founder Creator Status", status: "active", startDate: new Date("2026-03-10"), endDate: new Date("2026-04-10") } as any);
  await storage.createChallenge({ title: "Joshua Strategy Master Guide", slug: "joshua-strategy-master", description: "Write the definitive strategy guide for playing as Joshua. Cover his abilities, battle tactics, and how to unlock his maximum potential. Bonus points for scripture references.", type: "strategy", theme: "Joshua", rewardText: "Strategy Master Badge + Chronicles Lore Card", status: "active", startDate: new Date("2026-03-15"), endDate: new Date("2026-04-15") } as any);
  await storage.createChallenge({ title: "Design a New Faith Power", slug: "design-new-faith-power", description: "Create a brand new faith power ability for any Chronicles hero. Submit your design, name, description, and visual concept. Top submissions may actually be added to the game.", type: "fan art", theme: "Game Design", rewardText: "Game Designer Badge + Direct Message from the Dev Team", status: "upcoming", startDate: new Date("2026-04-01"), endDate: new Date("2026-04-30") } as any);
  await storage.createChallenge({ title: "Bible Reflection Inspired by Chronicles", slug: "bible-reflection-chronicles", description: "Write a personal Bible reflection on one of the battles or characters in Chronicles Reborn. How has playing the game changed your view of scripture? Minimum 300 words.", type: "reflection", theme: "Scripture", rewardText: "Faith Storyteller Badge + Founding Community Member Status", status: "active", startDate: new Date("2026-03-05"), endDate: new Date("2026-03-25") } as any);

  await storage.createChroniclesReward({ name: "First Post Badge", description: "Awarded for making your first Chronicles Reborn community post.", icon: "✍️", rewardType: "badge", unlockRule: "Make your first community post", rarity: "common" });
  await storage.createChroniclesReward({ name: "Challenge Champion", description: "Awarded for joining and completing your first Chronicles challenge.", icon: "⚔️", rewardType: "badge", unlockRule: "Submit to your first challenge", rarity: "uncommon" });
  await storage.createChroniclesReward({ name: "Community Beloved", description: "Awarded when your posts collectively receive 10 likes from the community.", icon: "❤️", rewardType: "badge", unlockRule: "Receive 10 total likes on your posts", rarity: "uncommon" });
  await storage.createChroniclesReward({ name: "Fan Artist", description: "Awarded for uploading your first piece of Chronicles fan art.", icon: "🎨", rewardType: "badge", unlockRule: "Upload your first fan art post", rarity: "common" });
  await storage.createChroniclesReward({ name: "Gameplay Creator", description: "Awarded for posting your first Chronicles gameplay clip.", icon: "🎮", rewardType: "badge", unlockRule: "Post your first gameplay clip", rarity: "common" });
  await storage.createChroniclesReward({ name: "Giant Slayer", description: "Exclusive wallpaper pack featuring the David vs Goliath battle in stunning detail.", icon: "🪨", rewardType: "wallpaper", unlockRule: "Win the Draw David vs Goliath challenge", rarity: "rare" });
  await storage.createChroniclesReward({ name: "Founding Creator", description: "A rare badge marking you as one of the original Chronicles Reborn community builders.", icon: "🏆", rewardType: "badge", unlockRule: "Join the community during the founding period (March 2026)", rarity: "legendary" });
  await storage.createChroniclesReward({ name: "Prophet of Fire", description: "Awarded to top Elijah content creators. Includes exclusive Elijah lore card.", icon: "🔥", rewardType: "lore_card", unlockRule: "Post 3 pieces of Elijah content that receive 50+ likes", rarity: "epic" });
  await storage.createChroniclesReward({ name: "Strategy Master", description: "Awarded to the creator of the most helpful Chronicles strategy content.", icon: "🧠", rewardType: "badge", unlockRule: "Create a strategy guide that receives 100+ likes", rarity: "rare" });
  await storage.createChroniclesReward({ name: "Battle Winner", description: "Awarded to challenge winners. A mark of honor in the Chronicles community.", icon: "🥇", rewardType: "badge", unlockRule: "Win a Chronicles challenge", rarity: "epic" });

  await storage.createCreatorProfile({ displayName: "Prophet Flame Art", creatorType: "Fan Artist", bio: "Digital artist and believer. I bring biblical battles to life through anime-inspired illustration. Every piece is a prayer.", badges: ["Fan Artist", "Founding Creator", "Giant Slayer"], featured: true, totalLikes: 1247, totalPosts: 34 });
  await storage.createCreatorProfile({ displayName: "StrategistKing", creatorType: "Strategist", bio: "I analyze Chronicles Reborn like it's a chess match. Legendary difficulty is my baseline. Strategy guides that actually work.", badges: ["Strategy Master", "Challenge Champion", "Founding Creator"], featured: true, totalLikes: 892, totalPosts: 27 });
  await storage.createCreatorProfile({ displayName: "ScriptureScholar", creatorType: "Faith Storyteller", bio: "Seminary student who found God's word in a video game. Chronicles Reborn made scripture come alive. I write about the theology behind the battles.", badges: ["Faith Storyteller", "Community Beloved"], featured: true, totalLikes: 756, totalPosts: 19 });
  await storage.createCreatorProfile({ displayName: "JoshuaCommander", creatorType: "Gameplay Creator", bio: "Speedrunner. Battle optimizer. Faith warrior. I play Chronicles like my life depends on it because spiritually, it does.", badges: ["Gameplay Creator", "Battle Winner", "Founding Creator"], featured: true, totalLikes: 634, totalPosts: 41 });
  await storage.createCreatorProfile({ displayName: "HolyMusicMaker", creatorType: "Music Creator", bio: "Producer and composer. Chronicles Reborn inspired my best work. Every track I release captures a different biblical battle.", badges: ["Music Creator", "Founding Creator"], featured: true, totalLikes: 521, totalPosts: 12 });
  await storage.createCreatorProfile({ displayName: "GideonFan300", creatorType: "Animator", bio: "Motion graphics artist. I animate the moments from Chronicles that give me chills. The Gideon torch scene changed my life.", badges: ["Fan Artist", "Challenge Champion"], featured: true, totalLikes: 489, totalPosts: 16 });

  console.log("Chronicles Reborn seed data complete!");
}
